name: kasie_transie_library
description: KasieTransie Library
version: 0.0.1
homepage:

environment:
  sdk: '>=3.0.2 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications: ^15.1.0+1
  cupertino_icons: ^1.0.5
  firebase_auth: ^4.6.3
  firebase_messaging: ^14.6.3
  firebase_core: ^2.14.0
  firebase_storage: ^11.2.3
  geofence_service: ^4.0.0
  geocoding: ^2.1.0
  path_provider: ^2.0.13
  provider: ^6.0.5
  material_design_icons_flutter: ^6.0.7096
  intl: ^0.18.0
  http: ^0.13.5
  device_info_plus: ^9.0.2
  image_picker: ^1.0.0
  universal_platform:
  focused_menu: ^1.0.5
  camera: ^0.10.5+2
  badges: ^3.1.1
  cached_network_image: ^3.2.3
  google_maps_flutter: ^2.3.0
  animated_splash_screen: ^1.3.0
  font_awesome_flutter: ^10.4.0
  page_transition: ^2.0.9
  responsive_builder: ^0.7.0
  animations: ^2.0.7
  flex_color_scheme: ^7.1.2
  firebase_crashlytics: ^3.3.3
  pin_code_fields: ^7.4.0
  geolocator: ^9.0.2
  maps_toolkit: ^2.0.1
  realm: ^1.2.0
  flutter_riverpod: ^2.3.6
  pretty_json: ^2.0.0
  dart_geohash: ^2.0.2
  proximity_hash: ^2.0.0
  fluttertoast: ^8.2.2
  equatable: ^2.0.5
  permission_handler: ^10.3.0
  qr_code_scanner: ^1.0.1
  workmanager: ^0.5.1
  audioplayers: ^4.1.0
  geojson: ^1.0.0
  location: ^4.4.0
  native_device_orientation: ^1.1.4
  image: ^4.0.17
  video_thumbnail: ^0.5.3
  beep_player: ^0.0.1
  open_mail_app: ^0.4.5
  firebase_dynamic_links: ^5.3.4
  get: ^4.6.5
  flutter_easyloading: ^3.0.5
  firebase_ui_auth: ^1.6.0
  account_picker: ^2.1.0
  sms_autofill: ^2.3.0
  numeric_keyboard: ^1.1.0
  mobile_number: ^2.1.1

  url_launcher:
  flutter_polyline_points:
  flutter_dotenv:



  dots_indicator:
  google_fonts:
  shared_preferences:
  package_info_plus: ^4.0.2
  play_integrity_flutter: ^0.0.1
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  build_runner: ^2.4.5
  hive_generator:
  mockito: ^5.4.1
  json_serializable: ^6.7.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
