name: kasie_transie_library
description: KasieTransie Library
version: 0.0.1
homepage:

environment:
  sdk: '>=3.0.2 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications: ^15.1.1
  cupertino_icons: ^1.0.6
  google_maps_flutter: ^2.5.0
  firebase_messaging: ^14.6.7
  firebase_core: ^2.15.1
  firebase_auth: ^4.9.0
  firebase_storage: ^11.2.6
  geofence_service: ^4.0.0
  geocoding: ^2.1.0
  path_provider: ^2.1.1
  provider: ^6.0.5
  material_design_icons_flutter: ^7.0.7296
  intl: ^0.18.1
  http: ^1.1.0
  device_info_plus: ^9.0.3
  image_picker: ^1.0.4
  universal_platform: ^1.0.0+1
  focused_menu: ^1.0.5
  camera: ^0.10.5+4
  badges: ^3.1.2
  cached_network_image: ^3.2.3
  animated_splash_screen: ^1.3.0
  font_awesome_flutter: ^10.5.0
  page_transition: ^2.1.0
  responsive_builder: ^0.7.0
  animations: ^2.0.8
  flex_color_scheme: ^7.3.1
  pin_code_fields: ^8.0.1
  geolocator: ^10.0.1
  maps_toolkit: ^2.0.1
  realm: ^1.4.0
  flutter_riverpod: ^2.3.7
  pretty_json: ^2.0.0
  dart_geohash: ^2.0.2
  proximity_hash: ^2.0.0
  fluttertoast: ^8.2.2
  equatable: ^2.0.5
  permission_handler: ^11.0.0
  qr_code_scanner: ^1.0.1
  geojson: ^1.0.0
#  location: ^4.4.0
  native_device_orientation: ^1.1.4
  image: ^4.0.17
  video_thumbnail: ^0.5.3
  open_mail_app: ^0.4.5
  firebase_dynamic_links: ^5.3.5
  get: ^4.6.6
  flutter_easyloading: ^3.0.5
  firebase_ui_auth: ^1.8.0
  account_picker: ^2.1.0
  sms_autofill: ^2.3.0
  numeric_keyboard: ^1.1.0
  mobile_number: ^2.1.1
  flutter_analog_clock: ^1.0.3
  custom_map_markers: ^0.0.2+1
  google_maps_cluster_manager: ^3.0.0+1
  firebase_analytics: ^10.4.5
  background_location: ^0.11.8
  url_launcher: ^6.1.14
  flutter_dotenv: ^5.1.0
  dots_indicator: ^3.0.0
  google_fonts: ^6.1.0
  shared_preferences: ^2.2.1
  package_info_plus: ^4.1.0
  play_integrity_flutter: ^0.0.1
  archive: ^3.3.9
  universal_io: ^2.2.2
  pinput: ^3.0.1
  intl_phone_field: ^3.2.0
  flutter_sim_country_code: ^0.1.2
  scrollable_positioned_list: ^0.3.8
  mobile_scanner: ^3.4.1
  get_it: ^7.6.4
  getwidget: ^4.0.0

#  realm_dart: ^1.4.0



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.2
  build_runner: ^2.4.6
  mockito: ^5.4.2
  json_serializable: ^6.7.1

flutter:
