name: kasie_transie_library
description: KasieTransie Library
version: 0.0.1
homepage:

environment:
  sdk: '>=3.0.2 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications: ^17.2.3
  cupertino_icons: ^1.0.8
  google_maps_flutter: ^2.9.0
  firebase_messaging: ^15.1.3
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  firebase_storage: ^12.3.2
  geofence_service: ^6.0.0
  geocoding: ^3.0.0
  path_provider: ^2.1.4
  provider: ^6.1.2
  material_design_icons_flutter: ^7.0.7296
  intl: ^0.19.0
  http: ^1.2.2
  device_info_plus: ^10.1.2
  image_picker: ^1.1.2
  universal_platform: ^1.1.0
  focused_menu: ^1.0.5
  camera: ^0.11.0+2
  badges: ^3.1.2
  cached_network_image: ^3.4.1
  animated_splash_screen: ^1.3.0
  font_awesome_flutter: ^10.7.0
  page_transition: ^2.1.0
  responsive_builder: ^0.7.1
  animations: ^2.0.11
  flex_color_scheme: ^7.3.1
  pin_code_fields: ^8.0.1
  geolocator: ^13.0.1
  maps_toolkit: ^3.0.0
  flutter_riverpod: ^2.5.1
  pretty_json: ^2.0.0
  dart_geohash: ^2.1.0
  proximity_hash: ^2.1.0
  fluttertoast: ^8.2.8
  equatable: ^2.0.5
  permission_handler: ^11.3.1
  geojson: ^1.0.0
  native_device_orientation: ^2.0.3
  image: ^4.2.0
  video_thumbnail: ^0.5.3
  open_mail_app: ^0.4.5
  firebase_dynamic_links: ^6.0.8
  get: ^4.6.6
  flutter_easyloading: ^3.0.5
  firebase_ui_auth: ^1.15.0
  account_picker: ^2.1.0
  sms_autofill: ^2.4.0
  numeric_keyboard: ^1.1.0
  mobile_number: ^2.1.1
  flutter_analog_clock: ^1.0.3
  custom_map_markers: ^0.0.2+1
  google_maps_cluster_manager: ^3.1.0
  firebase_analytics: ^11.3.3
  background_location: ^0.13.0
  url_launcher: ^6.3.0
  flutter_dotenv: ^5.1.0
  dots_indicator: ^3.0.0
  google_fonts: ^6.2.1
  shared_preferences: ^2.3.2
  package_info_plus: ^8.0.2
  play_integrity_flutter: ^0.0.1
  archive: ^3.6.1
  universal_io: ^2.2.2
  pinput: ^5.0.0
  intl_phone_field: ^3.2.0
  file_picker: ^8.1.2

  #  flutter_sim_country_code: ^0.1.2
  scrollable_positioned_list: ^0.3.8
  mobile_scanner: ^5.2.3
  get_it: ^8.0.0
  getwidget: ^4.0.0
  json_annotation: ^4.9.0
  mongo_dart: ^0.10.3
  country_calling_code_picker: ^2.0.1
  sembast_web: ^2.4.0+4



  flutter_sim_country_code: any
  uuid: any
  theme_mode_handler: ^3.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.11
  mockito: ^5.4.4
  json_serializable: ^6.8.0
#  realm_common: ^3.0.0

flutter:
