name: kasie_transie_library
description: KasieTransie Library
version: 0.0.1
homepage:

environment:
  sdk: '>=3.0.2 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications: any
  cupertino_icons: any
  google_maps_flutter: any
  firebase_messaging: any
  firebase_core: any
  firebase_auth: any
  firebase_storage: any
  geofence_service: any
  geocoding: any
  path_provider: any
  provider: any
#  material_design_icons_flutter: ^7.0.7296
  intl: any
  http: any
  device_info_plus: any
  image_picker: any
  universal_platform: any
  focused_menu: any
  camera: any
  badges: any
  cached_network_image: any
  animated_splash_screen: any
  font_awesome_flutter: any
  page_transition: any
  responsive_builder: any
  animations: any
  flex_color_scheme: any
  pin_code_fields: any
  geolocator: any
  maps_toolkit: any
#  flutter_riverpod: ^2.5.1
  pretty_json: any
  dart_geohash: any
  proximity_hash: any
  fluttertoast: any
  equatable: any
  permission_handler: any
  geojson: any
  native_device_orientation: any
  image: any
  firebase_dynamic_links: any
  get: any
  flutter_easyloading: any
  firebase_ui_auth: any
  sms_autofill: any
  numeric_keyboard: any
  flutter_analog_clock: any
  custom_map_markers: any
  google_maps_cluster_manager: any
  firebase_analytics: any
  url_launcher: any
  flutter_dotenv: any
  dots_indicator: any
  google_fonts: any
  shared_preferences: any
  package_info_plus: any
  archive: any
  universal_io: any
  pinput: any
  intl_phone_field: any
  scrollable_positioned_list: any
  get_it: any
  getwidget: any
  json_annotation: any
  sembast_web: any
  sembast: any
  uuid: any
  theme_mode_handler: any
  flutter_image_compress: any
  universal_html: any
  qr_flutter: any
  fast_csv: any
  sound_library: any
  barcode_scan2: any
  pretty_print_json: any
  widgets_to_image: any
  get_thumbnail_video: any
  qr_mobile_vision: any
  mobile_scanner: any
  google_mlkit_barcode_scanning: any
  currency_formatter: any
  file_picker: any
  flutter_data_table: any
  firebase_messaging_web: ^3.10.4


  google_mlkit_commons: any
  path: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any
  build_runner: any
  mockito: any
  json_serializable: any
  dependency_validator: any

flutter:
