// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2V3nU9omK0zOme_s_5fN43ju5h5s4vP8',
    appId: '1:610588876016:web:7f6aa2d05e73e9b9b53635',
    messagingSenderId: '610588876016',
    projectId: 'kasi-transie-2025',
    authDomain: 'kasi-transie-2025.firebaseapp.com',
    storageBucket: 'kasi-transie-2025.appspot.com',
    measurementId: 'G-YWJNF03JR1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgyJQ1kAQR_1o3k9xucdS9Ld4fcNdcrBc',
    appId: '1:610588876016:android:1a558333c3d3e8d3b53635',
    messagingSenderId: '610588876016',
    projectId: 'kasi-transie-2025',
    storageBucket: 'kasi-transie-2025.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-XMsTmzQzdq2PpDNytrI0UIZP_bcl5xY',
    appId: '1:610588876016:ios:40ff46b613cbe64cb53635',
    messagingSenderId: '610588876016',
    projectId: 'kasi-transie-2025',
    storageBucket: 'kasi-transie-2025.appspot.com',
    iosBundleId: 'com.boha.routes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-XMsTmzQzdq2PpDNytrI0UIZP_bcl5xY',
    appId: '1:610588876016:ios:40ff46b613cbe64cb53635',
    messagingSenderId: '610588876016',
    projectId: 'kasi-transie-2025',
    storageBucket: 'kasi-transie-2025.appspot.com',
    iosBundleId: 'com.boha.routes',
  );
}
